{{- if .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "log-generator.fullname" . }}-metrics
  {{- if .Values.api.serviceMonitor.namespace }}
  namespace: {{ .Values.api.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "log-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.api.serviceMonitor.additionalLabels }}
{{ toYaml .Values.api.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: api
      {{- if .Values.api.serviceMonitor.interval }}
      interval: {{ .Values.api.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.api.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.api.serviceMonitor.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "log-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}

