{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "log-generator.serviceAccountName" . }}
  labels:
{{ include "log-generator.labels" . | indent 4 }}
{{- end -}}
