apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-generator.fullname" . }}
  labels:
{{ include "log-generator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.addr }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "log-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
