apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: geoip-flow
  namespace: default
spec:
  filters: []
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  localOutputRefs:
    - null-output
