apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: geoip-flow
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
          types: size:integer,code:integer
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  localOutputRefs:
    - null-output
