apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: geoip-flow
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
          types: size:integer,code:integer
    - prometheus:
        metrics:
          - name: http_response_total
            desc: The total number of responses with code.
            type: counter
            labels:
              code: ${code}
        labels:
          app: log-generator
          pod: $.kubernetes.pod_name
          namespace: $.kubernetes.namespace_name
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  localOutputRefs:
    - null-output
